import { Theme } from '@vscodethemes/types'
import theme from '../theme'

const sym = Symbol()

export function isPlaceholder(obj: any) {
  return obj.__placeholder === sym
}

export default function generatePlaceholderThemes(count: number): Theme[] {
  return Array.from(new Array(count), (_, index) => ({
    __placeholder: sym,
    objectID: `placeholder-${index}`,
    extensionId: '',
    type: null,
    name: '',
    displayName: '',
    shortDescription: '',
    extensionName: '',
    publisherName: '',
    repository: '',
    repositoryOwner: '',
    repositoryBranch: '',
    repositoryPath: '',
    lastUpdated: -1,
    publishedDate: -1,
    releaseDate: -1,
    installs: -1,
    rating: -1,
    ratingCount: -1,
    trendingDaily: -1,
    trendingWeekly: -1,
    trendingMonthly: -1,
    colors: {
      // VSCode GUI
      activityBarBackground: theme.colors.background,
      activityBarForeground: theme.colors.background,
      statusBarBackground: theme.colors.background,
      statusBarForeground: theme.colors.background,
      editorBackground: theme.colors.background,
      editorForeground: theme.colors.background,
      editorGroupHeaderTabsBackground: theme.colors.background,
      editorGroupHeaderTabsBorder: theme.colors.background,
      editorLineNumberForeground: theme.colors.background,
      tabActiveBackground: theme.colors.background,
      tabActiveForeground: theme.colors.background,
      tabActiveBorder: theme.colors.background,
      tabBorder: theme.colors.inputBorder,
      tabInactiveBackground: theme.colors.background,
      tabInactiveForeground: theme.colors.background,
      contrastActiveBorder: null,
      contrastBorder: null,
      // Tokens
      commentForeground: theme.colors.background,
      commentFontStyle: 'normal',
      punctuationForeground: theme.colors.background,
      punctuationFontStyle: 'normal',
      keywordForeground: theme.colors.background,
      keywordFontStyle: 'normal',
      classForeground: theme.colors.background,
      classFontStyle: 'normal',
      literalForeground: theme.colors.background,
      literalFontStyle: 'normal',
      numberForeground: theme.colors.background,
      numberFontStyle: 'normal',
      stringForeground: theme.colors.background,
      stringFontStyle: 'normal',
      variableForeground: theme.colors.background,
      variableFontStyle: 'normal',
      operatorForeground: theme.colors.background,
      operatorFontStyle: 'normal',
      functionForeground: theme.colors.background,
      functionFontStyle: 'normal',
      functionParamForeground: theme.colors.background,
      functionParamFontStyle: 'normal',
      tagForeground: theme.colors.background,
      tagFontStyle: 'normal',
      attributeForeground: theme.colors.background,
      attributeFontStyle: 'normal',
      attributeValueForeground: theme.colors.background,
      attributeValueFontStyle: 'normal',
      propertyForeground: theme.colors.background,
      propertyFontStyle: 'normal',
      selectorForeground: theme.colors.background,
      selectorFontStyle: 'normal',
    },
  }))
}
