import { Theme } from '../../types/static'
import theme from '../theme'

export default function generatePlaceholderThemes(count: number): Theme[] {
  return Array.from(new Array(count), (_, index) => ({
    objectID: `placeholder-${index}`,
    extensionId: '',
    type: null,
    name: '',
    shortDescription: '',
    extensionName: '',
    publisherName: '',
    repository: '',
    repositoryOwner: '',
    repositoryBranch: '',
    repositoryPath: '',
    lastUpdated: -1,
    publishedDate: -1,
    releaseDate: -1,
    installs: -1,
    rating: -1,
    ratingCount: -1,
    trendingDaily: -1,
    trendingWeekly: -1,
    trendingMonthly: -1,
    colors: {
      activityBarBackground: theme.colors.background,
      activityBarForeground: theme.colors.textMuted,
      statusBarBackground: theme.colors.background,
      statusBarForeground: theme.colors.textMuted,
      editorBackground: theme.colors.background,
      editorGroupHeaderTabsBackground: theme.colors.background,
      editorGroupHeaderTabsBorder: theme.colors.background,
      editorLineNumberForeground: theme.colors.background,
      tabActiveBackground: theme.colors.background,
      tabActiveForeground: theme.colors.textMuted,
      tabActiveBorder: theme.colors.background,
      tabBorder: theme.colors.inputBorder,
      tabInactiveBackground: theme.colors.background,
      tabInactiveForeground: theme.colors.textMuted,
      contrastActiveBorder: null,
      contrastBorder: null,
    },
    tokens: {
      keywordForeground: null,
      keywordFontStyle: null,
      variableForeground: null,
      variableFontStyle: null,
      literalForeground: null,
      literalFontStyle: null,
      numberForeground: null,
      numberFontStyle: null,
      stringForeground: null,
      stringFontStyle: null,
      commentForeground: null,
      commentFontStyle: null,
      classForeground: null,
      classFontStyle: null,
      functionForeground: null,
      functionFontStyle: null,
      selectorForeground: null,
      selectorFontStyle: null,
      tagForeground: null,
      tagFontStyle: null,
      attributeForeground: null,
      attributeFontStyle: null,
    },
  }))
}
